version: "3.7"
services:
  db:
    image: mysql
    restart: "always"
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: "GitEval"
    volumes:
      - "./db:/var/lib/mysql"
  GitEval:
    # 本地镜像
    image: "giteval:v1"
    restart: "always"
    volumes:
      - "./config/backend/config.yaml:/app/conf/config.yaml"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - llm
      - redis
  redis:
    image: 'bitnami/redis:7.2'
    environment:
      - ALLOW_EMPTY_PASSWORD=no    # 禁止空密码
      - REDIS_PASSWORD=muxistudio304  # 设置密码为 muxistudio304
    ports:
      - '6379:6379'    
  llm:
    image: "llm:v1"
    restart: "always"
    volumes:
      - "./config/llm/config.yaml:/app/config/config.yaml"
    ports:
      - "11028:11028"